version: '3.8'

services:
  server:
    image: timer_chatbot:develop
    container_name: timer_chatbot
    depends_on:
      - redis
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./apps:/apps
    command: streamlit run main.py 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  redis:
    image: redis:latest
    container_name: timer_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local