version: '3.8'

services:
  server:
    image: timer_chatbot:develop
    container_name: timer_chatbot
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./apps:/apps
    command: streamlit run frontend/main.py 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 5